services:
  bot:
    container_name: bot-box_recorder
    build:
      context: ./bot
      dockerfile: Dockerfile # Certifique-se que o arquivo se chama "Dockerfile" (com D mai√∫sculo)
    environment:
      - DISPLAY=:99
    restart: unless-stopped